### ISSUE TITLE
RuntimeError: Invalid DISPLAY variable error

### ISSUE THREAD

**Issue by change2014** [rafaelpadilla/Object-Detection-Metrics#81]
I am getting the below error 
Traceback (most recent call last):
  File "pascalvoc.py", line 331, in <module>
    showGraphic=showPlot)
  File "/data/model_assess/Object-Detection-Metrics/lib/Evaluator.py", line 221, in PlotPrecisionRecallCurve
    plt.plot(recall, precision, label='Precision')
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/matplotlib/pyplot.py", line 3347, in plot
    ax = gca()
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/matplotlib/pyplot.py", line 984, in gca
    return gcf().gca(**kwargs)
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/matplotlib/pyplot.py", line 601, in gcf
    return figure()
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/matplotlib/pyplot.py", line 548, in figure
    **kwargs)
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 167, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure)
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 24, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 234, in __init__
    _create_qApp()
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 125, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
Can anyone please help me debug this?

**Comment by rafaelpadilla** [comment]
Dear @change2014,

What version of the matplotlib are you using?

Have you created the environment using the [requirements.txt ](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/requirements.txt) file?

**Comment by rafaelpadilla** [comment]
@change2014,

Were you able to solve this problem? May I close this issue?

**Comment by change2014** [comment]
yes, please close the issue.
